CREATE DATABASE IF NOT EXISTS zhitu
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS hive_metastore
  DEFAULT CHARACTER SET latin1
  DEFAULT COLLATE latin1_swedish_ci;

CREATE USER IF NOT EXISTS 'hive'@'%' IDENTIFIED BY 'hive123456';
GRANT ALL PRIVILEGES ON hive_metastore.* TO 'hive'@'%';

CREATE USER IF NOT EXISTS 'zhitu'@'%' IDENTIFIED BY 'zhitu123456';
GRANT ALL PRIVILEGES ON zhitu.* TO 'zhitu'@'%';

FLUSH PRIVILEGES;
